name: flutter_app_template
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  dio: ^5.3.0
  logger: any
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  # fftea: ^1.5.0
  # wav: ^1.3.0
  # assets_audio_player: ^3.1.1
  # just_audio: ^0.9.36
  # flutter_fft: ^1.0.2+6
  flutter_soloud: ^1.2.4
  ffi: ^2.0.2
  statsfl: ^2.3.0


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  surf_lint_rules: ^3.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/shaders/
    - assets/test.wav
    - assets/test.mp3
